apiVersion: v1
data:
  MYSQL_PASSWORD: bXlzcWxwYXNz
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNz
kind: Secret
metadata:
  creationTimestamp: "2026-02-23T05:10:20Z"
  name: common-secret
  namespace: default
  resourceVersion: "1566"
  uid: 1e661074-8e7e-4afa-9177-168c3704f2ed
type: Opaque
