apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-02-23T05:36:40Z"
  labels:
    app: wordpress
  name: wordpress-service
  namespace: default
  resourceVersion: "2797"
  uid: a343dc33-9113-46b8-931f-22cd17294136
spec:
  clusterIP: 10.111.241.183
  clusterIPs:
  - 10.111.241.183
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30423
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
